### ISSUE TITLE
How to specify JWT bearer Type in openapi generation

### ISSUE THREAD

**Issue by jabalsad** [awslabs/smithy#825]
Hi,

I'm trying to use a `@httpBearerAuth` trait on my service, that specifies the `bearerFormat` as `JWT`. How do I do this using the current trait?

I'd like to generate an openapi specification that has these lines in it:
```
  securitySchemes:    
    bearerAuth:      
      type: http      
      scheme: bearer      
      bearerFormat: JWT
```
